/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as LandingRouteImport } from './routes/landing'
import { Route as MyTripsRouteImport } from './routes/my-trips'
import { Route as PriceAlertsRouteImport } from './routes/price-alerts'
import { Route as ProcessingRouteImport } from './routes/processing'
import { Route as DashboardIdRouteImport } from './routes/dashboard.$id'
import { Route as ApiPublicHooksCheckFlightPriceAlertsRouteImport } from './routes/api/public/hooks/check-flight-price-alerts'
import { Route as ApiPublicHooksSendFlightPriceAlertEmailRouteImport } from './routes/api/public/hooks/send-flight-price-alert-email'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const LandingRoute = LandingRouteImport.update({
  id: '/landing',
  path: '/landing',
  getParentRoute: () => rootRouteImport,
} as any)
const MyTripsRoute = MyTripsRouteImport.update({
  id: '/my-trips',
  path: '/my-trips',
  getParentRoute: () => rootRouteImport,
} as any)
const PriceAlertsRoute = PriceAlertsRouteImport.update({
  id: '/price-alerts',
  path: '/price-alerts',
  getParentRoute: () => rootRouteImport,
} as any)
const ProcessingRoute = ProcessingRouteImport.update({
  id: '/processing',
  path: '/processing',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIdRoute = DashboardIdRouteImport.update({
  id: '/dashboard/$id',
  path: '/dashboard/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksCheckFlightPriceAlertsRoute =
  ApiPublicHooksCheckFlightPriceAlertsRouteImport.update({
    id: '/api/public/hooks/check-flight-price-alerts',
    path: '/api/public/hooks/check-flight-price-alerts',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksSendFlightPriceAlertEmailRoute =
  ApiPublicHooksSendFlightPriceAlertEmailRouteImport.update({
    id: '/api/public/hooks/send-flight-price-alert-email',
    path: '/api/public/hooks/send-flight-price-alert-email',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/landing': typeof LandingRoute
  '/my-trips': typeof MyTripsRoute
  '/price-alerts': typeof PriceAlertsRoute
  '/processing': typeof ProcessingRoute
  '/dashboard/$id': typeof DashboardIdRoute
  '/api/public/hooks/check-flight-price-alerts': typeof ApiPublicHooksCheckFlightPriceAlertsRoute
  '/api/public/hooks/send-flight-price-alert-email': typeof ApiPublicHooksSendFlightPriceAlertEmailRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/landing': typeof LandingRoute
  '/my-trips': typeof MyTripsRoute
  '/price-alerts': typeof PriceAlertsRoute
  '/processing': typeof ProcessingRoute
  '/dashboard/$id': typeof DashboardIdRoute
  '/api/public/hooks/check-flight-price-alerts': typeof ApiPublicHooksCheckFlightPriceAlertsRoute
  '/api/public/hooks/send-flight-price-alert-email': typeof ApiPublicHooksSendFlightPriceAlertEmailRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/landing': typeof LandingRoute
  '/my-trips': typeof MyTripsRoute
  '/price-alerts': typeof PriceAlertsRoute
  '/processing': typeof ProcessingRoute
  '/dashboard/$id': typeof DashboardIdRoute
  '/api/public/hooks/check-flight-price-alerts': typeof ApiPublicHooksCheckFlightPriceAlertsRoute
  '/api/public/hooks/send-flight-price-alert-email': typeof ApiPublicHooksSendFlightPriceAlertEmailRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/landing'
    | '/my-trips'
    | '/price-alerts'
    | '/processing'
    | '/dashboard/$id'
    | '/api/public/hooks/check-flight-price-alerts'
    | '/api/public/hooks/send-flight-price-alert-email'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/landing'
    | '/my-trips'
    | '/price-alerts'
    | '/processing'
    | '/dashboard/$id'
    | '/api/public/hooks/check-flight-price-alerts'
    | '/api/public/hooks/send-flight-price-alert-email'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/landing'
    | '/my-trips'
    | '/price-alerts'
    | '/processing'
    | '/dashboard/$id'
    | '/api/public/hooks/check-flight-price-alerts'
    | '/api/public/hooks/send-flight-price-alert-email'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  LandingRoute: typeof LandingRoute
  MyTripsRoute: typeof MyTripsRoute
  PriceAlertsRoute: typeof PriceAlertsRoute
  ProcessingRoute: typeof ProcessingRoute
  DashboardIdRoute: typeof DashboardIdRoute
  ApiPublicHooksCheckFlightPriceAlertsRoute: typeof ApiPublicHooksCheckFlightPriceAlertsRoute
  ApiPublicHooksSendFlightPriceAlertEmailRoute: typeof ApiPublicHooksSendFlightPriceAlertEmailRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/landing': {
      id: '/landing'
      path: '/landing'
      fullPath: '/landing'
      preLoaderRoute: typeof LandingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-trips': {
      id: '/my-trips'
      path: '/my-trips'
      fullPath: '/my-trips'
      preLoaderRoute: typeof MyTripsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/price-alerts': {
      id: '/price-alerts'
      path: '/price-alerts'
      fullPath: '/price-alerts'
      preLoaderRoute: typeof PriceAlertsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/processing': {
      id: '/processing'
      path: '/processing'
      fullPath: '/processing'
      preLoaderRoute: typeof ProcessingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/$id': {
      id: '/dashboard/$id'
      path: '/dashboard/$id'
      fullPath: '/dashboard/$id'
      preLoaderRoute: typeof DashboardIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/check-flight-price-alerts': {
      id: '/api/public/hooks/check-flight-price-alerts'
      path: '/api/public/hooks/check-flight-price-alerts'
      fullPath: '/api/public/hooks/check-flight-price-alerts'
      preLoaderRoute: typeof ApiPublicHooksCheckFlightPriceAlertsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/send-flight-price-alert-email': {
      id: '/api/public/hooks/send-flight-price-alert-email'
      path: '/api/public/hooks/send-flight-price-alert-email'
      fullPath: '/api/public/hooks/send-flight-price-alert-email'
      preLoaderRoute: typeof ApiPublicHooksSendFlightPriceAlertEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  LandingRoute: LandingRoute,
  MyTripsRoute: MyTripsRoute,
  PriceAlertsRoute: PriceAlertsRoute,
  ProcessingRoute: ProcessingRoute,
  DashboardIdRoute: DashboardIdRoute,
  ApiPublicHooksCheckFlightPriceAlertsRoute:
    ApiPublicHooksCheckFlightPriceAlertsRoute,
  ApiPublicHooksSendFlightPriceAlertEmailRoute:
    ApiPublicHooksSendFlightPriceAlertEmailRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
